language: node_js
nodejs:
- "7"
cache:
  directories:
  - node_modules
before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_0.49.2_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
install:
  - npm install
script:
  - gulp stylelint
  - gulp eslint
  - npm run build
